KyosenaCV/urls.py
from django.urls import path
from . import views

app_name = 'KyosenaCV'

urlpatterns = [
    path('', views.index, name='index'),
    path('Resume/', views.Resume, name='Resume'),
    path('AboutMe/', views.AboutMe, name = 'AboutMe'),
    # dilanjutkan ...
]

Story/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('KyosenaCV.urls')),
]

KyosenaCV/models.py
from django.db import models

# Create your models here.

KyosenaCV/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def Resume(request):
    return render(request, 'Resume.html')

def AboutMe(request):
    return render(request,'AboutMe.html')

KyosenaCV/templates/AboutMe.html
<!DOCTYPE HTML>
{% load static %}
<html id ='aboutmehtml'>
    <head>
            <title> Welcome</title>
            <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
            <script type="text/javascript" src ="script.js"></script>
            <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
             <link rel ="stylesheet" href="{% static 'css/main.css' %}">
    </head>
    <body id = 'aboutme'>
        <div id = 'backgroundaboutme'></div>
        <div id = "headmenu">
            <a href = '{%url "KyosenaCV:index" %}'><button class = "headitem"> <b>Home</b></button></a>
            <a href = '{%url "KyosenaCV:Resume" %}'><button class = "headitem"> Resume</button></a>
            <button class = "headitem"> About me</button>
        </div>
        <div class = 'back'>
            <a href = "javascript:history.back()"c><button class = 'backbutton'><span><< </span>Back</button></a>
        </div>
        <div class = 'pnd'>
            <div class ='pndpicture'></div>
            
        </div>
        <div class ='pndtitle'>
            <p>PASSIONS AND DREAMS</p>
        </div>
        <div class ='pndcontent'>
            I was born in <b>Jakarta,</b> the metropolitan capital of Indonesia. It is only natural for me to have an affinity for tech and graphical design, seeing how virtually anything inside the rustling and bustling hometown of mine are all connected digitally. It is my dream to one day not just be a part of it, but to influence it through graphic design.
        </div>
        <div class = 'ane'>
            <div class ='anepicture'></div>
        </div>
        <div class = 'anetitle'>
            <p>ADAPTABLE AND EVOLVING</p>
        </div>
        <div class= 'anecontent'>
            <p>
                Coming from where I came and having met the people I have, I can confidenty say that I have a substantial experience in working with diverse people from many walks of life. I’m always looking for ways to evolve and improve my efficiency. I can adapt to ever changing situations swiftly, turning risks and obstacles into oppurtunities that can be exploited. 
            </p>
        </div>
        <div class = 'mystery'>
           
        </div>
        <div class ='mysterypicture'></div>
        <div class = 'mysterytitle'>
            <p> WHAT'S LIFE WITHOUT A BIT OF MYSTERY?</p>
        </div>
        <div class = 'mysterycontent'>
            <p>If you’ve read all of this, then I’m going to assume that I’ve peaked your interest. I would love to tell you all about myself, but what’s life without a bit of mystery? Whether it would be through work or purely social endeavours, I hope we can get to know each other better.</p>
        </div>

    </body>
</html>

KyosenaCV/templates/Resume.html
<!DOCTYPE HTML>
{% load static %}
<html>
    <head>
        <title> Welcome</title>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <script type="text/javascript" src ="script.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
        <link rel ="stylesheet" href="{% static 'css/main.css' %}">
    </head>
    <body id = 'Resume'>
        <div id = 'backgroundimage'></div>
        <div id = "headmenu">
            <a href = "{%url 'KyosenaCV:index' %}"><button class = "headitem"> Home</button></a>
            <button class = "headitem"><b> Resume</b></button>
            <a href = '{%url "KyosenaCV:AboutMe" %}'><button class = "headitem"> About me</button></a>
        </div>
        <div class = 'back'>
            <a href = "javascript:history.back()"><button class = 'backbutton'><span><< </span>Back</button></a>
        </div>
        <div class = 'bio'>
            <img id = 'biopic' src ="{% static 'images/1053947.jpg' %}" alt = "Kyo"height = 28% width = 20% px >
            <div class = 'lightwhitebox' id = "info">
                 <p> Name : Kyosena Haridza </p>
                 <p> Address : Apartemen Grand Taman <br> Melati</p>
                 <p> Phone : 081380805130</p>
                 <p> Email : Kyosenaharidza@gmail.com</p>
            </div>
            <div class = 'lightyellowbox' id = 'desc'>
                <p id ='biodesc'> Biography :</p>
                 <p id = 'description'> I'm a 19 year old college student who's looking for new experiences to widen my field of view and improve my proficiency. I get along well with all kinds of people and love teamwork. </p>
            </div>
            <div class = 'descstyle'></div>
            
        </div>
        <div class = 'SW'>
            <div class = 'lightbrownbox' id = 'Strengths'>
                <p>Strengths:</p>
                <div id = 'boast'>
                    <p> -Socializing </p>
                    <p>-Fast-Integration and highly adaptable</p>
                    <p>-Tech-savvy</p>
                    <p>-High-energy and motivated</p>
                 </div>
            </div>
            <div class = "StrengthStyle"></div>
            <div class = 'darkbluebox' id ='Weaknesses'>
                    <p> Weaknesses:</p>
                    <div id = 'humbling'>
                     <p> -I may talk too much</p>
                    <p> -Calculus</p>
                    <p> -Aloof in certain subjects</p>
                    </div>
                
            </div>
            <div class = "WeaknessStyle"></div>
            
        </div>
        <div class = 'education'>
            <div class = 'lightbluebox' id = 'formal'>
                <p> Education:</p>
                <div id = 'formaleducation'>
                    <p class = 'location'> -Universitas Indonesia</p>
                    <p class = 'detail'> Bachelor's degree in computer <br> science</p>
                    <p class = 'location'> -SMAN 81</p>
                    <p class = 'detail'> High School Diploma</p>
                    <p class = 'location'> -SMPN 115</p>
                    <p class = 'detail'> Middle School Diploma</p>
                </div>
                
            </div>
            <div class = 'FormalStyle'></div>
            <div class ='darkredbox' id = 'non-formal'>
                <p>Non-Formal Education:</p>
                <div id ='non-formaleducation'>
                    <p class = 'location'> -Ganesha Operation</p>
                    <p class = 'detail'> High School Level</p>
                    <p class = 'location'> -Inten </p>
                    <p class = 'detail'> Middle School Level</p>
                    <p class = 'location'>-Primagama</p>
                    <p class = 'detail'> Elementary Level</p>
                </div>
            </div>
            <div class = 'NonformalStyle'></div>
        </div>
        <div class ='likesndislikes'>
            <div class ='darkgreenbox' id = 'likes'>
                <p> Likes:</p>
                <div class = 'interests'>
                    <p> Anything Technology Related</p>
                    <p> Making Friends and meeting people</p>
                    <p> Video Games</p>
                    <p> Travelling</p>
                    <p> Cinematography</p>
                </div>
            </div> 
            <div class ='LikeStyle'></div>
            <div class = 'darkpurplebox' id = 'dislikes'>
                <p> Dislikes:</p>
                <div class ='disinterests'>
                    <p> Indie Music</p>
                    <p> Anything Spiritual</p>
                    <p> Gossip</p>
                    <p> Pretentiousness</p>
                    <p> Loud People</p>
                </div>
            </div >
            <div class = 'DislikeStyle'></div>

            </div>
        </div>
    </body>
        

KyosenaCV/templates/index.html
<!DOCTYPE HTML>
{% load static %}
<html>
    <head>
            <title> Welcome</title>
            <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
             <link rel ="stylesheet" href="{% static 'css/main.css' %}"">
    </head>
    <body id ='indexbody'>
            <div id = "headmenu">
                <button class = "headitem"> <b>Home</b></button>
                <a href = '{%url "KyosenaCV:Resume" %}'><button class = "headitem"> Resume</button></a>
                <a href ='{%url "KyosenaCV:AboutMe" %}'><button class = "headitem"> About me</button></a>
            </div>
            <div class = "splash" align = center>
                <p id='title'>Kyosena<img id = "portrait"  src ="static/images/Sharp.jpg" align = 'center' alt = "a very handsome man" width="250" height="250">Haridza</p>
        </div>
            <div class ="hi" align = center>
                <p>  Hi there. I'm Kyo. <br>
                    Let's make something <b id="beauty"> beautiful.</b></p>
        </div>
        <div class = 'sosmed' align = center>
            <a href ='https://www.instagram.com/kyosenaharidza/' target = 'popup'><img  id = "instagram" src="static/images/instagram.png" alt = "an instagram logo"  width = "70" height = "70"></a>
            <a href = 'https://id.linkedin.com/in/kyosena-haridza-2b363816b' target = 'popup'><img id ="linkedin" align = 'bottom' src="static/images/linkedin1.png" alt = "a linkedin logo"  width = "78"  height="78"></a>
        </div>
        <div id ='gradient'></div>
    </body>
    
</html>